In [ ]:
#import libraries  
import numpy as np
import pandas as pd 
from transformers import AutoModelForSequenceClassification, BertForSequenceClassification
from transformers import pipeline
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer, AutoConfig
from scipy.special import softmax

In [3]:
classifier = pipeline('sentiment-analysis')

Downloading: 100%|██████████| 442/442 [00:00<00:00, 75.2kB/s]
Downloading: 100%|██████████| 232k/232k [00:01<00:00, 131kB/s]
Downloading: 100%|██████████| 629/629 [00:00<00:00, 209kB/s]
Downloading: 100%|██████████| 230/230 [00:00<00:00, 68.1kB/s]
Downloading: 100%|██████████| 268M/268M [02:22<00:00, 1.88MB/s]

In [18]:
res = classifier('i got a job as a Data Analytics')

In [19]:
print(res)

[{'label': 'POSITIVE', 'score': 0.99907005}]

In [ ]:
df = pd.read_csv('cleanDf.csv')

In [17]:
df.head()

,Unnamed: 0,user,Messages,Lenguage,SwipesRight,SwipesLeft,Matches,Num Of Messages,Age
0,1,1534e9,"Hello again, so now that we matched again, wha...",['en'],45068.0,45068.0,888.0,2086.0,25.0
1,1,1534e9,"Most of the girls on this app scare me, but fo...",['en'],45068.0,45068.0,888.0,2086.0,25.0
2,1,1534e9,"Dear diary, cute girl vanished... should I sen...",['en'],45068.0,45068.0,888.0,2086.0,25.0
3,1,1534e9,"Most of the girls on this app scare me, but fo...",['en'],45068.0,45068.0,888.0,2086.0,25.0
4,1,1534e9,"Well not many people have photos of dogs, and ...",['en'],45068.0,45068.0,888.0,2086.0,25.0

In [21]:
#extract the column Messages to have it as an input for the sentiment analysis 
messages = df['Messages']

In [ ]:
#from the 1.5 million conversations we keep only 493,396 for the sentiment ansalysis. 
sentiment = []
sentScore = []
for message in messages:
    output = classifier(message)
    label = output[0]['label']
    score = output[0]['score']
    sentiment.append(label)
    sentScore.append(score)

In [68]:
#create a copy of the data frame
newDf = df.copy()

In [69]:
#keep 493.396 rows to run our linear model
newDf.drop(index=newDf.index[493395:-1],axis=0,inplace=True)

In [70]:
#
newDf.insert(3, 'Sentiment', sentiment)
newDf.insert(4, 'SentScore', sentScore)

In [71]:
newDf.head()

,Unnamed: 0,user,Messages,Sentiment,SentScore,Lenguage,SwipesRight,SwipesLeft,Matches,Num Of Messages,Age
0,1,1534e9,"Hello again, so now that we matched again, wha...",POSITIVE,0.989172,['en'],45068.0,45068.0,888.0,2086.0,25.0
1,1,1534e9,"Most of the girls on this app scare me, but fo...",POSITIVE,0.997748,['en'],45068.0,45068.0,888.0,2086.0,25.0
2,1,1534e9,"Dear diary, cute girl vanished... should I sen...",NEGATIVE,0.999569,['en'],45068.0,45068.0,888.0,2086.0,25.0
3,1,1534e9,"Most of the girls on this app scare me, but fo...",NEGATIVE,0.625871,['en'],45068.0,45068.0,888.0,2086.0,25.0
4,1,1534e9,"Well not many people have photos of dogs, and ...",NEGATIVE,0.996307,['en'],45068.0,45068.0,888.0,2086.0,25.0

In [72]:
#export to csv
newDf.to_csv('sentimentAnalysis .csv', encoding='utf-8')

In [ ]:
lenguage = newDf['Language']

In [80]:
# from sklearn.preprocessing import OneHotEncoder

oheDf = pd.get_dummies(data=newDf, columns=['Language'])

In [81]:
oheDf.head()

,Unnamed: 0,user,Messages,Sentiment,SentScore,SwipesRight,SwipesLeft,Matches,Num Of Messages,Age,...,Lenguage_['nl'],Lenguage_['no'],Lenguage_['pl'],Lenguage_['pt'],Lenguage_['ro'],Lenguage_['ru'],Lenguage_['so'],Lenguage_['sv'],Lenguage_['sw'],Lenguage_['zh-cn']
0,1,1534e9,"Hello again, so now that we matched again, wha...",POSITIVE,0.989172,45068.0,45068.0,888.0,2086.0,25.0,...,0,0,0,0,0,0,0,0,0,0
1,1,1534e9,"Most of the girls on this app scare me, but fo...",POSITIVE,0.997748,45068.0,45068.0,888.0,2086.0,25.0,...,0,0,0,0,0,0,0,0,0,0
2,1,1534e9,"Dear diary, cute girl vanished... should I sen...",NEGATIVE,0.999569,45068.0,45068.0,888.0,2086.0,25.0,...,0,0,0,0,0,0,0,0,0,0
3,1,1534e9,"Most of the girls on this app scare me, but fo...",NEGATIVE,0.625871,45068.0,45068.0,888.0,2086.0,25.0,...,0,0,0,0,0,0,0,0,0,0
4,1,1534e9,"Well not many people have photos of dogs, and ...",NEGATIVE,0.996307,45068.0,45068.0,888.0,2086.0,25.0,...,0,0,0,0,0,0,0,0,0,0